# Generated by Django 5.2.14 on 2026-05-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('taluka', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('nivada_number', models.CharField(blank=True, max_length=100, null=True)),
                ('nivada_date', models.CharField(blank=True, max_length=100, null=True)),
                ('survey_number', models.CharField(blank=True, max_length=100, null=True)),
                ('gat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('land_area', models.CharField(blank=True, max_length=100, null=True)),
                ('volume_number', models.BigIntegerField(blank=True, null=True)),
                ('file_number', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['district', 'taluka', 'village'],
                'indexes': [models.Index(fields=['district'], name='land_record_distric_8e5909_idx'), models.Index(fields=['taluka'], name='land_record_taluka_a15889_idx'), models.Index(fields=['village'], name='land_record_village_595b2d_idx'), models.Index(fields=['survey_number'], name='land_record_survey__40eb02_idx'), models.Index(fields=['gat_number'], name='land_record_gat_num_e19086_idx'), models.Index(fields=['project_name'], name='land_record_project_8918e1_idx')],
            },
        ),
    ]
