# Generated by Django 5.2.14 on 2026-05-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_records', '0002_reportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrecord',
            name='nivada_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
