# Generated by Django 5.2.14 on 2026-05-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_records', '0003_landrecord_nivada_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
