# Generated by Django 5.2.14 on 2026-05-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_records', '0004_reportrequest_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landrecord',
            name='nivada_name',
        ),
        migrations.AddField(
            model_name='landrecord',
            name='Nvd_Name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
