# Generated by Django 5.2.14 on 2026-05-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_records', '0005_remove_landrecord_nivada_name_landrecord_nvd_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivada',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nvd_office', models.CharField(blank=True, max_length=255, null=True)),
                ('nvd_district', models.CharField(blank=True, max_length=255, null=True)),
                ('nvd_tahsil', models.CharField(blank=True, max_length=255, null=True)),
                ('nvd_village', models.CharField(blank=True, max_length=255, null=True)),
                ('nvd_project', models.TextField(blank=True, null=True)),
                ('nvd_nivada', models.CharField(blank=True, max_length=100, null=True)),
                ('nvd_nivadadate', models.CharField(blank=True, max_length=100, null=True)),
                ('nvd_nivadadt', models.CharField(blank=True, max_length=100, null=True)),
                ('nvd_name', models.TextField(blank=True, null=True)),
                ('nvd_survey', models.CharField(blank=True, max_length=100, null=True)),
                ('nvd_gatno', models.CharField(blank=True, max_length=100, null=True)),
                ('nvd_gat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('nvd_area', models.CharField(blank=True, max_length=100, null=True)),
                ('nvd_fileno', models.CharField(blank=True, max_length=255, null=True)),
                ('nvd_remarks', models.TextField(blank=True, null=True)),
                ('volume_no', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nivada',
                'managed': False,
            },
        ),
    ]
