# Generated by Django 5.2.14 on 2026-06-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_records', '0006_nivada'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='nivada_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
