# Generated by Django 5.2.14 on 2026-06-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_records', '0007_reportrequest_nivada_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerMaster',
            fields=[
                ('officer_id', models.IntegerField(db_column='OfficerId', primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, db_column='District', max_length=255, null=True)),
                ('taluka', models.CharField(blank=True, db_column='Taluka', max_length=255, null=True)),
                ('village', models.CharField(blank=True, db_column='Village', max_length=255, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
                ('officer_name', models.CharField(db_column='Officer_Name', max_length=255)),
                ('email_id', models.EmailField(blank=True, db_column='Email_Id', max_length=254, null=True)),
                ('contact_no', models.CharField(blank=True, db_column='Contact_No', max_length=100, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('from_date', models.DateField(blank=True, db_column='From_Date', null=True)),
                ('to_date', models.DateField(blank=True, db_column='To_Date', null=True)),
                ('designation_id', models.IntegerField(blank=True, db_column='Designation_Id', null=True)),
            ],
            options={
                'db_table': 'Officer_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.BigIntegerField()),
                ('officer_id', models.IntegerField(blank=True, null=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_district', models.CharField(max_length=255)),
                ('address_taluka', models.CharField(max_length=255)),
                ('address_village', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('taluka', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('generated_pdf_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Certificate_Request',
            },
        ),
    ]
