# Generated by Django 5.2.14 on 2026-06-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_records', '0008_officermaster_certificaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='gat_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='nivada_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='project_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='survey_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
