# Generated by Django 5.2.14 on 2026-06-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_records', '0009_certificaterequest_gat_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='signed_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='signed_certificates/'),
        ),
    ]
