# Generated by Django 5.2.14 on 2026-06-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_records', '0010_certificaterequest_pdf_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.IntegerField(db_column='Designation_Id', primary_key=True, serialize=False)),
                ('designation', models.CharField(db_column='Designation', max_length=255)),
            ],
            options={
                'db_table': 'mstDesignation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanPg',
            fields=[
                ('document_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('volume_no', models.BigIntegerField()),
                ('page_no', models.BigIntegerField()),
                ('imageimg', models.BinaryField()),
                ('thumbimg', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scanpg',
                'managed': False,
            },
        ),
    ]
