# Generated by Django 5.2.14 on 2026-06-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_records', '0011_designation_scanpg'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='entryno',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='page_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='volume_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
