# Generated by Django 6.0.6 on 2026-09-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_records', '0012_certificaterequest_entryno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionProofRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.BigIntegerField()),
                ('volume_no', models.BigIntegerField(blank=True, null=True)),
                ('page_no', models.BigIntegerField(blank=True, null=True)),
                ('entryno', models.BigIntegerField(blank=True, null=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('district', models.CharField(max_length=255)),
                ('taluka', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('nivada_name', models.TextField(blank=True, null=True)),
                ('survey_number', models.CharField(blank=True, max_length=255, null=True)),
                ('gat_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('proof_document', models.FileField(upload_to='acquisition_proofs/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Valid', 'Valid'), ('Invalid', 'Invalid')], default='Pending', max_length=20)),
                ('officer_remarks', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.IntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Acquisition_Proof_Request',
            },
        ),
    ]
