# Generated by Django 6.0.6 on 2026-09-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_records', '0013_acquisitionproofrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisitionproofrequest',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='acquisitionproofrequest',
            name='district',
        ),
        migrations.RemoveField(
            model_name='acquisitionproofrequest',
            name='entryno',
        ),
        migrations.RemoveField(
            model_name='acquisitionproofrequest',
            name='nivada_name',
        ),
        migrations.RemoveField(
            model_name='acquisitionproofrequest',
            name='page_no',
        ),
        migrations.RemoveField(
            model_name='acquisitionproofrequest',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='acquisitionproofrequest',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='acquisitionproofrequest',
            name='volume_no',
        ),
    ]
